### ISSUE TITLE
Support for vaadin v 24.5?

### ISSUE THREAD

**Issue by gmerton** [mstahv/flow-with-jwt-authentication#1]
Hello!
I tried naively bumping the vaadin version up on this project to 24.5.7 and it blew up.  Would it be a major refactor to support it?

Many thanks for all your work!

**Comment by mstahv** [comment]
Are you getting this error?:

```
java.lang.NoClassDefFoundError: org/apache/commons/codec/digest/DigestUtils
	at com.vaadin.copilot.analytics.AnalyticsClient.<init>(AnalyticsClient.java:44) ~[copilot-24.6.0.jar:na]
	at com.vaadin.copilot.analytics.AnalyticsClient.getInstance(AnalyticsClient.java:59) ~[copilot-24.6.0.jar:na]
	at com.vaadin.copilot.CopilotIndexHtmlLoader.serviceInit(CopilotIndexHtmlLoader.java:45) ~[copilot-24.6.0.jar:na]
	at com.vaadin.flow.server.VaadinService.lambda$init$0(VaadinService.java:271) ~[flow-server-24.6.0.jar:24.6.0]
```

Some version conflict introduced by copilot 🤔 Probably excluding it is the easiest solution.

**Comment by mstahv** [comment]
It was quite a fight, but this commit seems to get at least to some extent working project:

https://github.com/mstahv/flow-with-jwt-authentication/commit/f19ffec17f325266dfa1b8c23e11cf6a9cbe3f50

**Comment by mstahv** [comment]
There is still a part that is using a deprecated version of Spring Security API, but fixing that ought to be easy.

**Comment by gmerton** [comment]
Confirmed!  It works great.  Many thanks for your work on this... I know housekeeping can be dull, but this really helps me out.  

In terms of feature requests, does your team like to receive those in GitHub Issues?  If not, I can add some comments on the blog.  They're mostly related to [the replace cookies in every request](https://github.com/vaadin/flow/pull/18994) change that occurred in 24.3.9
